version: '3'

services:

  #Nginx
  nginx:
    image: nginx:alpine
    container_name: lemp_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.logs/nginx:/var/log/nginx
    networks:
      - lemp_network
    links:
      - php

  #PHP
  php:
    build: ./php-fpm
    container_name: lemp_php_fpm
    ports:
      - "9000:9000"
    volumes:
      - ./www/html:/var/www/html
    networks:
      - lemp_network

  #MariaDB
  mariadb:
    image: mariadb:latest
    container_name: lemp-mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./.data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - lemp_network

  #phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lemp_pma
    environment:
      PMA_HOST: mariadb
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - lemp_network

#Networks
networks:
  lemp_network:
    driver: bridge